language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  - source cfg4dev
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
after_success:
  - ./dockerfiles/build-docker-images.sh $DOCKER_EMAIL $DOCKER_USERNAME $DOCKER_PASSWORD ./dist/gaming_spiders-*.*.*.tar.gz
