language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  - DOCKER_TEMP_IMAGE_NAME=simonsdave/gaming-spiders:bindle
install:
  - source cfg4dev
  - docker pull koalaman/shellcheck:latest
script:
  - flake8
  - docker run -v "$PWD:/mnt" koalaman/shellcheck:latest $(find . -name \*.sh | grep -v \.\/env)
  - travis_fold start "build.python.packages"
  - python setup.py bdist_wheel sdist --formats=gztar
  - travis_fold end "build.python.packages"
  - travis_fold start "build.docker.image"
  - ./dockerfiles/build-docker-image.sh ./dist/gaming_spiders-*.*.*.tar.gz $DOCKER_TEMP_IMAGE_NAME
  - travis_fold end "build.docker.image"
  - run_all_spiders.sh --image $DOCKER_TEMP_IMAGE_NAME
deploy:
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh $DOCKER_TEMP_IMAGE_NAME $DOCKER_USERNAME $DOCKER_PASSWORD latest
    on:
      branch: master
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh $DOCKER_TEMP_IMAGE_NAME $DOCKER_USERNAME $DOCKER_PASSWORD $TRAVIS_TAG
    on:
      tags: true
