language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  - source cfg4dev
  - docker pull koalaman/shellcheck:latest
script:
  - pycodestyle
  - flake8
  - docker run -v "$PWD:/mnt" koalaman/shellcheck:latest $(find . -name \*.sh | grep -v \.\/env)
  - python setup.py bdist_wheel sdist --formats=gztar
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then
      DOCKER_IMAGE_NAME=$(./dockerfiles/docker-image-name.sh "$DOCKER_USERNAME" "$TRAVIS_TAG")
      ./dockerfiles/build-docker-image.sh ./dist/gaming_spiders-*.*.*.tar.gz "$DOCKER_IMAGE_NAME" "$DOCKER_USERNAME" "$DOCKER_PASSWORD"
      run_all_spiders.sh --image "$DOCKER_IMAGE_NAME"
    fi
