language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  - source cfg4dev
  - google-chrome --version
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
  - run_all_spiders.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-images.sh -v -t "$TRAVIS_TAG" ./dist/gaming_spiders-*.*.*.tar.gz $DOCKER_USERNAME $DOCKER_EMAIL $DOCKER_PASSWORD; fi
