language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  # these new few lines (upto 'google-chrome --version') are
  # here to upgrade the installed version of chrome after
  # upgrading to version 22 of ChromeDriver
  - curl -s https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
  - google-chrome --version
  - source cfg4dev
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
  - run_all_spiders.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-images.sh -v -t "$TRAVIS_TAG" ./dist/gaming_spiders-*.*.*.tar.gz $DOCKER_USERNAME $DOCKER_EMAIL $DOCKER_PASSWORD; fi
