language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  - source cfg4dev
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
  - cp dist/gaming_spiders-*.*.*.tar.gz spiders.tar.gz
  - sudo docker build -t simonsdave/gaming-spiders .
after_success:
  - sudo docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - sudo docker push simonsdave/gaming-spiders
