---
version: 2.1

executors:
  dev-env:
    docker:
      - image: simonsdave/cloudfeaster-xenial-dev-env:v0.9.21

jobs:
  build_test_and_package:
    working_directory: ~/repo
    executor: dev-env
    steps:
      - checkout
      - run: check-consistent-clf-version.sh --verbose
      - run: check-circleci-config.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Python prerequisites
          command: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: run-pip-check.sh
      - run:
          name: Lint Python Files
          command: run-flake8.sh
      - run:
          name: PyCQA/bandit
          command: run-bandit.sh
      - run:
          name: Lint Shell Scripts
          command: run-shellcheck.sh
      - run:
          name: Lint YAML Files
          command: run-yamllint.sh
      - run:
          name: Scan repo for passwords, private keys, etc.
          command: run-repo-security-scanner.sh
      - run:
          name: Snyk vulnerability assessment
          command: run-snyk.sh "$SNYK_TOKEN"
      - run:
          name: Run unit tests
          command: run-unit-tests.sh
      - run:
          name: Build python packages
          command: build-python-package.sh
      - persist_to_workspace:
          root: dist
          paths:
            - gaming_spiders-*.whl
            - gaming_spiders-*.tar.gz
  run_spider_bigfishonlinegames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: bigfishonlinegames.py
  run_spider_gamehouseonlinegames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: gamehouseonlinegames.py
  run_spider_gamesonly:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: gamesonly.py
  run_spider_hiddenobjectgames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: hiddenobjectgames.py
  run_spider_mahjonggames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: mahjonggames.py
  run_spider_match3games:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: match3games.py
  run_spider_mindgames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: mindgames.py
  run_spider_miniclip:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: miniclip.py
  run_spider_msnonlinegames:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: msnonlinegames.py
  run_spider_solitaireonline:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: solitaireonline.py
  save_artifacts:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  build_test_and_save_artifacts:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_test_and_package:
          context: gaming-spiders
      - run_spider_bigfishonlinegames:
          requires:
            - build_test_and_package
      - run_spider_gamehouseonlinegames:
          requires:
            - build_test_and_package
      - run_spider_gamesonly:
          requires:
            - build_test_and_package
      - run_spider_hiddenobjectgames:
          requires:
            - build_test_and_package
      - run_spider_mahjonggames:
          requires:
            - build_test_and_package
      - run_spider_match3games:
          requires:
            - build_test_and_package
      - run_spider_mindgames:
          requires:
            - build_test_and_package
      - run_spider_miniclip:
          requires:
            - build_test_and_package
      - run_spider_msnonlinegames:
          requires:
            - build_test_and_package
      - run_spider_solitaireonline:
          requires:
            - build_test_and_package
      - save_artifacts:
          requires:
            - run_spider_bigfishonlinegames
            - run_spider_gamehouseonlinegames
            - run_spider_gamesonly
            - run_spider_hiddenobjectgames
            - run_spider_mahjonggames
            - run_spider_match3games
            - run_spider_mindgames
            - run_spider_miniclip
            - run_spider_msnonlinegames
            - run_spider_solitaireonline
