---
version: 2.1

executors:
  dev-env:
    docker:
      - image: simonsdave/cloudfeaster-dev-env:v0.9.44
        auth:
          username: $DOCKER_EXECUTOR_DOCKERHUB_USERNAME
          password: $DOCKER_EXECUTOR_DOCKERHUB_PASSWORD

jobs:
  build_test_package_and_save_artifacts:
    working_directory: ~/repo
    executor: dev-env
    steps:
      - checkout
      - run: check-consistent-clf-version.sh --verbose
      # :TODO: :TEMP: until upgrade to next cloudfeaster rev
      # - run: check-circleci-config.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Python prerequisites
          command: python3.7 -m pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run pip check
          command: run-pip-check.sh
      - run:
          name: Lint Python Files
          command: run-flake8.sh
      - run:
          name: PyCQA/bandit
          command: run-bandit.sh
      - run:
          name: Lint Shell Scripts
          command: run-shelllint.sh --verbose
      - run:
          name: Lint Markdown Files
          command: run-markdownlint.sh --verbose
      - run:
          name: Lint YAML Files
          command: run-yamllint.sh --verbose
      - run:
          name: Lint JSON Files
          command: run-jsonlint.sh --verbose
      - run:
          name: Scan repo for passwords, private keys, etc.
          command: run-repo-security-scanner.sh
      - run:
          name: Run unit tests
          command: run-unit-tests.sh
      - run:
          name: Build README.rst
          command: build-readme-dot-rst.sh
      - run:
          name: Build python packages
          command: build-python-package.sh
      - store_artifacts:
          path: dist
          destination: dist
      - persist_to_workspace:
          root: dist
          paths:
            - gaming_spiders-*.whl
            - gaming_spiders-*.tar.gz
  run_spider:
    executor: dev-env
    parameters:
      spider:
        type: string
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: python3.7 -m pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: |
            mkdir /tmp/<< parameters.spider >>
            CRAWL_OUTPUT=/tmp/<< parameters.spider >>/crawl-output.json
            #
            # need the "|| true" because bash started by CircleCI with -e
            # and shell will exit when spider fails which is exactly what
            # we don't want because then we don't get access to artifacts
            # to diagnose the spider's failure
            #
            # why is CLF_DEBUG set to DEBUG? theory here is that if a
            # problem occours the more info we have to debug the better!
            #
            CLF_DEBUG=DEBUG << parameters.spider >>.py >& "${CRAWL_OUTPUT}" || true
            jq -r . "${CRAWL_OUTPUT}"
            #
            # the store_artifacts steps below will tolerate artifacts
            # *not* being present by the cp commands will not be as tolerant
            # if jq output is "null" and hence the complexity of the if
            # statements below to improve robustness
            #
            if [[ "$(jq -r ._debug.screenshot ${CRAWL_OUTPUT})" != "null" ]]; then
              cp $(jq -r ._debug.screenshot "${CRAWL_OUTPUT}") /tmp/<< parameters.spider >>/screenshot.png
            fi
            if [[ "$(jq -r ._debug.crawlLog ${CRAWL_OUTPUT})" != "null" ]]; then
              cp $(jq -r ._debug.crawlLog "${CRAWL_OUTPUT}") /tmp/<< parameters.spider >>/crawl-log.txt
            fi
            if [[ "$(jq -r ._debug.chromeDriverLog ${CRAWL_OUTPUT})" != "null" ]]; then
              cp $(jq -r ._debug.chromeDriverLog "${CRAWL_OUTPUT}") /tmp/<< parameters.spider >>/chrome-driver-log.txt
            fi
      - store_artifacts:
          path: /tmp/<< parameters.spider >>/crawl-output.json
          destination: crawl-output.json
      - store_artifacts:
          path: /tmp/<< parameters.spider >>/screenshot.png
          destination: screenshot.png
      - store_artifacts:
          path: /tmp/<< parameters.spider >>/crawl-log.txt
          destination: crawl-log.txt
      - store_artifacts:
          path: /tmp/<< parameters.spider >>/chrome-driver-log.txt
          destination: chrome-driver-log.txt
      - run:
          name: fail workflow if crawl failed
          command: |
            #
            # we force the "run spider" step to succeed regardless of the
            # success/failure of the spider's crawl. however, we actually
            # want the workflow to fail if the spider's crawl fails but we
            # also want to store artifacts before failing because those
            # artifacts will be used to debug a failed crawl. this is all
            # to explain the need for this somewhat odd final step in the
            # workflow.
            #
            if [[ "$(jq ._metadata.status.code /tmp/<< parameters.spider >>/crawl-output.json)" != "0" ]]; then
                false
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build_test_package_and_save_artifacts:
          context:
            - gaming-spiders
            - docker-executor
      - run_spider:
          spider: bigfishonlinegames
          name: run_spider_bigfishonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: gamehouseonlinegames
          name: run_spider_gamehouseonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: gamesonly
          name: run_spider_gamesonly
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: hiddenobjectgames
          name: run_spider_hiddenobjectgames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: mahjonggames
          name: run_spider_mahjonggames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: match3games
          name: run_spider_match3games
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: mindgames
          name: run_spider_mindgames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: miniclip
          name: run_spider_miniclip
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: msnonlinegames
          name: run_spider_msnonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: solitaireonline
          name: run_spider_solitaireonline
          requires:
            - build_test_package_and_save_artifacts
  nightly:
    triggers:
      - schedule:
          # https://crontab.guru/ is super useful in decoding the value of the cron key
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_test_package_and_save_artifacts:
          context:
            - gaming-spiders
            - docker-executor
      - run_spider:
          spider: bigfishonlinegames
          name: run_spider_bigfishonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: gamehouseonlinegames
          name: run_spider_gamehouseonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: gamesonly
          name: run_spider_gamesonly
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: hiddenobjectgames
          name: run_spider_hiddenobjectgames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: mahjonggames
          name: run_spider_mahjonggames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: match3games
          name: run_spider_match3games
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: mindgames
          name: run_spider_mindgames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: miniclip
          name: run_spider_miniclip
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: msnonlinegames
          name: run_spider_msnonlinegames
          requires:
            - build_test_package_and_save_artifacts
      - run_spider:
          spider: solitaireonline
          name: run_spider_solitaireonline
          requires:
            - build_test_package_and_save_artifacts
