---
version: 2.1

executors:
  dev-env:
    docker:
      - image: simonsdave/cloudfeaster-xenial-dev-env:v0.9.23

jobs:
  build_test_and_package:
    working_directory: ~/repo
    executor: dev-env
    steps:
      - checkout
      - run: check-consistent-clf-version.sh --verbose
      - run: check-circleci-config.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Python prerequisites
          command: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: run-pip-check.sh
      - run:
          name: Lint Python Files
          command: run-flake8.sh
      - run:
          name: PyCQA/bandit
          command: run-bandit.sh
      - run:
          name: Lint Shell Scripts
          command: run-shellcheck.sh
      - run:
          name: Lint YAML Files
          command: run-yamllint.sh
      - run:
          name: Scan repo for passwords, private keys, etc.
          command: run-repo-security-scanner.sh
      - run:
          name: Snyk vulnerability assessment
          command: run-snyk.sh "$SNYK_TOKEN"
      - run:
          name: Run unit tests
          command: run-unit-tests.sh
      - run:
          name: Build python packages
          command: build-python-package.sh
      - persist_to_workspace:
          root: dist
          paths:
            - gaming_spiders-*.whl
            - gaming_spiders-*.tar.gz
  run_spider:
    executor: dev-env
    parameters:
      spider:
        type: string
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: spider install from dist
          command: pip install dist/gaming_spiders*.tar.gz
      - run:
          name: run spider
          command: << parameters.spider >>.py
  save_artifacts:
    executor: dev-env
    steps:
      - attach_workspace:
          at: dist
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  commit:
    jobs:
      - build_test_and_package:
          context: gaming-spiders
      - run_spider:
          spider: bigfishonlinegames
          name: run_spider_bigfishonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: gamehouseonlinegames
          name: run_spider_gamehouseonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: gamesonly
          name: run_spider_gamesonly
          requires:
            - build_test_and_package
      - run_spider:
          spider: hiddenobjectgames
          name: run_spider_hiddenobjectgames
          requires:
            - build_test_and_package
      - run_spider:
          spider: mahjonggames
          name: run_spider_mahjonggames
          requires:
            - build_test_and_package
      - run_spider:
          spider: match3games
          name: run_spider_match3games
          requires:
            - build_test_and_package
      - run_spider:
          spider: mindgames
          name: run_spider_mindgames
          requires:
            - build_test_and_package
      - run_spider:
          spider: miniclip
          name: run_spider_miniclip
          requires:
            - build_test_and_package
      - run_spider:
          spider: msnonlinegames
          name: run_spider_msnonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: solitaireonline
          name: run_spider_solitaireonline
          requires:
            - build_test_and_package
      - save_artifacts:
          requires:
            - run_spider_bigfishonlinegames
            - run_spider_gamehouseonlinegames
            - run_spider_gamesonly
            - run_spider_hiddenobjectgames
            - run_spider_mahjonggames
            - run_spider_match3games
            - run_spider_mindgames
            - run_spider_miniclip
            - run_spider_msnonlinegames
            - run_spider_solitaireonline
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_test_and_package:
          context: gaming-spiders
      - run_spider:
          spider: bigfishonlinegames
          name: run_spider_bigfishonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: gamehouseonlinegames
          name: run_spider_gamehouseonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: gamesonly
          name: run_spider_gamesonly
          requires:
            - build_test_and_package
      - run_spider:
          spider: hiddenobjectgames
          name: run_spider_hiddenobjectgames
          requires:
            - build_test_and_package
      - run_spider:
          spider: mahjonggames
          name: run_spider_mahjonggames
          requires:
            - build_test_and_package
      - run_spider:
          spider: match3games
          name: run_spider_match3games
          requires:
            - build_test_and_package
      - run_spider:
          spider: mindgames
          name: run_spider_mindgames
          requires:
            - build_test_and_package
      - run_spider:
          spider: miniclip
          name: run_spider_miniclip
          requires:
            - build_test_and_package
      - run_spider:
          spider: msnonlinegames
          name: run_spider_msnonlinegames
          requires:
            - build_test_and_package
      - run_spider:
          spider: solitaireonline
          name: run_spider_solitaireonline
          requires:
            - build_test_and_package
      - save_artifacts:
          requires:
            - run_spider_bigfishonlinegames
            - run_spider_gamehouseonlinegames
            - run_spider_gamesonly
            - run_spider_hiddenobjectgames
            - run_spider_mahjonggames
            - run_spider_match3games
            - run_spider_mindgames
            - run_spider_miniclip
            - run_spider_msnonlinegames
            - run_spider_solitaireonline
