version: 2

_defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: simonsdave/cloudfeaster-xenial-dev-env:v0.9.16

jobs:
  build_test_and_save_artifacts:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Python prerequisites
          command: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: run-pip-check.sh
      - run: run-flake8.sh
      - run: 
          name: Lint bash scripts
          command: run-shellcheck.sh -v
      - run: 
          name: Scan repo for passwords, private keys, etc.
          command: run-repo-security-scanner.sh
      - run:
          name: Snyk vulnerability assessment
          command: run-snyk.sh "$SNYK_TOKEN"
      - run: 
          name: Run unit tests
          command: run-unit-tests.sh
      - run: 
          name: Build python packages
          command: build-python-package.sh

workflows:
  version: 2
  build_test_and_save_artifacts:
    jobs:
      - build_test_and_save_artifacts:
          context: gaming-spiders
