FROM simonsdave/cloudfeaster-lite:v%CLF_VERSION%

MAINTAINER Dave Simons

ENV DEBIAN_FRONTEND noninteractive

COPY package.tar.gz /tmp/package.tar.gz
RUN python3.7 -m pip install /tmp/package.tar.gz
RUN rm -f /tmp/package.tar.gz

ENV DEBIAN_FRONTEND newt
