FROM simonsdave/cloudfeaster-xenial-dev-env:%CLF_VERSION%

LABEL maintainer="Dave Simons"

ARG PACKAGE

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /tmp/package
ADD package.tar.gz /tmp/package/.

RUN cd /tmp/package && pip install --requirement "requirements.txt"

RUN rm -rf "/tmp/package"

ENV DEBIAN_FRONTEND newt
