FROM simonsdave/cloudfeaster-bionic-dev-env:%CLF_VERSION%

LABEL maintainer="Dave Simons"

ENV DEBIAN_FRONTEND noninteractive

COPY package.tar.gz /tmp/.
RUN python3.7 -m pip install /tmp/package.tar.gz
RUN rm -f /tmp/package.tar.gz

ENV DEBIAN_FRONTEND newt
