"""Zygomatic has a number of online gaming portals that all
seem to use the same platform. This module contains an asbstract
base class which will crawl sites generated by this platform.
"""

from cloudfeaster import spider


class ZygomaticSpider(spider.Spider):

    def crawl(self, browser):

        data = {}

        for rank in range(1, 11):
            link_locator = "//div[@class='index block-group']/div[%d]/a" % rank
            link_element = browser.find_element_by_xpath(link_locator)
            link = link_element.get_attribute("href")

            title_locator = "//div[@class='index block-group']/div[%d]/a/div/h3" % rank
            title_element = browser.find_element_by_xpath(title_locator)
            title = title_element.get_text()

            data[rank] = {
                "title": title,
                "link": link,
            }

        return spider.CrawlResponseOk(data)
